### ISSUE TITLE
Push edits to github.

### ISSUE THREAD

**Issue by gracel0** [geekwise-grace-liang/django-drf-react-bank-todo#11]

**Comment by gracel0** [comment]
@geekwise-yuki-xiong
Yuki, please help.  I can't push to github. What's wrong?

**Comment by geekwise-grace-liang** [comment]
![Screen Shot 2020-02-10 at 7 05 23 PM](https://user-images.githubusercontent.com/57422235/74208680-70f25d00-4c39-11ea-9d65-5abc041b00be.png)

**Comment by geekwise-grace-liang** [comment]
![Screen Shot 2020-02-10 at 7 12 20 PM](https://user-images.githubusercontent.com/57422235/74208747-b31b9e80-4c39-11ea-913e-b8cdfba5c69b.png)

**Comment by geekwise-yuki-xiong** [comment]
Use 
```git push origin -u master```

**Comment by gracel0** [comment]
Thanks, Yuki.
```git push origin -u master``` works!
