### ISSUE TITLE
API urls in debug.backend branch.

### ISSUE THREAD

**Issue by geekwise-grace-liang** [geekwise-grace-liang/django-drf-react-bank-todo#6]

**Comment by geekwise-grace-liang** [comment]
@geekwise-yuki-xiong, @geekwise-maria-navarro Could you please take a look at what I might have done wrong following the tutorial for Django React Todo?  

Is urls.py file supposed to be in the Main folder or outside of it?  Is the code correct?  I think I have have mix of the tutorial and drf stuff.  I'm trying to get to the CRUD process.  Thank you!

![image](https://user-images.githubusercontent.com/57422235/71533981-8fcaa900-28b0-11ea-857f-564dec69cffc.png)

![image](https://user-images.githubusercontent.com/57422235/71533992-9bb66b00-28b0-11ea-8916-2f00690d0afd.png)

**Comment by geekwise-maria-navarro** [comment]
@geekwise-grace-liang 
The urls should be under main.

**Comment by geekwise-grace-liang** [comment]
It works the way it is! Yay.

To get api, need to type URL/api/.

Examples:
URL/api/todos/it
URL/api/todos/description
URL/api/todos/completed
